package site.addzero.platform.lowcode.generator

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertFalse
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test

class ConventionFileSourceGeneratorTest {
    @Test
    fun `generates editable service and scheduled job convention files`() {
        val files = ConventionFileSourceGenerator.generate(
            listOf(
                conventionFile("refreshCatalog", "RefreshCatalogJob", LsiConventionFileKind.SCHEDULED_JOB),
                conventionFile("catalog", "CatalogService", LsiConventionFileKind.SERVICE),
            ),
        )

        assertEquals(listOf("CatalogService", "RefreshCatalogJob"), files.map(LowcodeGeneratedFile::fileName))
        assertTrue(files.all { file -> file.kind == LowcodeGeneratedFileKind.CONVENTION_FILE_SCAFFOLD })
        assertTrue(files.all { file -> file.content.startsWith("// generated by studio") })
        val service = files.first()
        assertEquals("example.catalog.service", service.packageName)
        assertTrue(service.relativePath.endsWith("/service/CatalogService.kt"))
        assertTrue(service.content.contains("@Single\nclass CatalogService"))
        assertFalse(service.content.contains("request"))
        assertFalse(service.content.contains("response"))
        val job = files.last()
        assertEquals("example.catalog.job", job.packageName)
        assertTrue(job.relativePath.endsWith("/job/RefreshCatalogJob.kt"))
        assertTrue(job.content.contains("class RefreshCatalogJob : ScheduledJob"))
        assertTrue(job.content.contains("override val schedule: String = \"0 0 0 * * * 480o\""))
        assertTrue(job.content.contains("override suspend fun execute() = Unit"))
    }

    private fun conventionFile(
        code: String,
        className: String,
        kind: LsiConventionFileKind,
    ) = LsiConventionFile(
        fileCode = code,
        name = className,
        className = className,
        kind = kind,
        packageName = "example.catalog",
        contributorId = "example.library",
    )
}
