package site.addzero.platform.lowcode.generator

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertFalse
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test

class LowcodeFeatureServiceSourceGeneratorTest {
    @Test
    fun `model without operations does not generate dangling service`() {
        val model = model()
        val feature = LsiLowcodeFeature(
            featureCode = "internal",
            name = "Internal",
            packageName = model.packageName,
            contributorId = model.contributorId!!,
            modelCodes = listOf(model.modelCode),
        )
        val route = routeBinding(model).let { binding ->
            binding.copy(route = binding.route.copy(enabledOperations = emptySet()))
        }

        val files = LowcodeFeatureServiceSourceGenerator.generate(
            features = listOf(feature),
            models = listOf(model),
            contracts = emptyList(),
            routeBindings = listOf(route),
        )

        assertTrue(files.isEmpty())
    }

    @Test
    fun `generates entity services without a dangling feature aggregate`() {
        val model = model()
        val contract = LsiLowcodeContract(
            contractCode = "publicJob",
            name = "公开招聘",
            packageName = "example.recruitment",
            className = "PublicJobService",
            path = "/jobs",
            contributorId = model.contributorId,
        )
        val feature = LsiLowcodeFeature(
            featureCode = "recruitment",
            name = "招聘管理",
            packageName = "example.recruitment",
            contributorId = model.contributorId!!,
            modelCodes = listOf(model.modelCode),
            contractCodes = listOf(contract.contractCode),
        )

        val files = LowcodeFeatureServiceSourceGenerator.generate(
            features = listOf(feature),
            models = listOf(model),
            contracts = listOf(contract),
            routeBindings = listOf(routeBinding(model)),
        )

        assertEquals(
            listOf("SiteJobService", "SiteJobServiceImpl"),
            files.map(LowcodeGeneratedFile::fileName),
        )
        val entityService = files.single { file -> file.fileName == "SiteJobService" }
        val implementation = files.single { file -> file.fileName == "SiteJobServiceImpl" }
        assertEquals(LowcodeGeneratedFileKind.COMPILED_SOURCE, entityService.kind)
        assertEquals(LowcodeGeneratedFileKind.SERVICE_IMPLEMENTATION_SCAFFOLD, implementation.kind)
        assertTrue(files.all { file -> file.content.startsWith("// generated by studio") })
        assertTrue(entityService.content.contains("interface SiteJobService : IService<SiteJob>"))
        assertFalse(entityService.content.contains("LowcodeRestContract"))
        assertFalse(entityService.content.contains("SiteJobLowcodeContract"))
        assertTrue(implementation.content.lineSequence().any { line -> line == "@Single" })
        assertTrue(
            implementation.content.lineSequence().any { line ->
                line.startsWith(LowcodeFeatureServiceSourceGenerator.SERVICE_IMPLEMENTATION_SIGNATURE_PREFIX)
            },
        )
        assertFalse(implementation.content.contains("LowcodeContractResolver"))
        assertFalse(implementation.content.contains("LowcodeRouteRuntimeProvider"))
        assertFalse(implementation.content.contains("entityClass ="))
        assertFalse(implementation.content.contains("modelCode ="))
        assertTrue(implementation.content.contains("class SiteJobServiceImpl : ServiceImpl<SiteJob>(), SiteJobService"))
        assertFalse(entityService.content.contains("IExcelService"))
        assertFalse(implementation.content.contains("ExcelServiceImpl"))
        assertFalse(implementation.content.contains("LowcodeCrudOperationsProvider"))
        assertFalse(implementation.content.contains("LowcodeRuntimeController"))
        assertFalse(files.any { file -> file.fileName == "RecruitmentService" })
        assertFalse(files.any { file -> file.fileName.endsWith("CrudService") })
        assertTrue(entityService.relativePath.endsWith("/service/SiteJobService.kt"))
        assertTrue(implementation.relativePath.endsWith("/service/SiteJobServiceImpl.kt"))
        assertTrue(
            files.all { file ->
                file.content.lineSequence().none { line -> line.isNotEmpty() && line.last().isWhitespace() }
            },
        )
    }

    @Test
    fun `model only feature generates entity service without empty feature service`() {
        val model = model()
        val feature = LsiLowcodeFeature(
            featureCode = "recruitment",
            name = "招聘管理",
            packageName = "example.recruitment",
            contributorId = model.contributorId!!,
            modelCodes = listOf(model.modelCode),
        )

        val files = LowcodeFeatureServiceSourceGenerator.generate(
            features = listOf(feature),
            models = listOf(model),
            contracts = emptyList(),
            routeBindings = listOf(routeBinding(model)),
        )

        assertEquals(listOf("SiteJobService", "SiteJobServiceImpl"), files.map(LowcodeGeneratedFile::fileName))
    }

    @Test
    fun `service only entity still generates CRUD service`() {
        val model = model()
        val feature = LsiLowcodeFeature(
            featureCode = "recruitment",
            name = "招聘管理",
            packageName = model.packageName,
            contributorId = model.contributorId!!,
            modelCodes = listOf(model.modelCode),
        )
        val binding = routeBinding(model).let { value ->
            value.copy(route = value.route.copy(generateController = false))
        }

        val files = LowcodeFeatureServiceSourceGenerator.generate(
            features = listOf(feature),
            models = listOf(model),
            contracts = emptyList(),
            routeBindings = listOf(binding),
        )

        assertEquals(listOf("SiteJobService", "SiteJobServiceImpl"), files.map(LowcodeGeneratedFile::fileName))
    }

    @Test
    fun `excel metadata generates typed excel service and implementation`() {
        val model = model()
        val feature = LsiLowcodeFeature(
            featureCode = "recruitment",
            name = "招聘管理",
            packageName = "example.recruitment",
            contributorId = model.contributorId!!,
            modelCodes = listOf(model.modelCode),
        )
        val column = LsiLowcodeProperty(
            name = "name",
            type = "string",
            format = null,
            required = true,
            arrayItemType = null,
            description = "名称",
        )

        val files = LowcodeFeatureServiceSourceGenerator.generate(
            features = listOf(feature),
            models = listOf(model),
            contracts = emptyList(),
            routeBindings = listOf(
                routeBinding(
                    model,
                    LsiLowcodeExcel(
                        importEnabled = true,
                        exportEnabled = true,
                        customExport = false,
                        fileName = "jobs",
                        templateFileName = "jobs-template",
                        sheetName = "jobs",
                        importColumns = listOf(column),
                        exportColumns = listOf(column),
                    ),
                ),
            ),
        )

        val entityService = files.single { file -> file.fileName == "SiteJobService" }
        val implementation = files.single { file -> file.fileName == "SiteJobServiceImpl" }
        assertTrue(entityService.content.contains("interface SiteJobService : IExcelService<SiteJob>"))
        assertFalse(entityService.content.contains("interface SiteJobService : IService<SiteJob>"))
        assertTrue(implementation.content.contains("ExcelServiceImpl<SiteJob>"))
        assertFalse(implementation.content.contains("site.addzero.platform.lowcode"))
    }

    private fun model() = LowcodeModelMeta(
        id = 1,
        modelCode = "siteJob",
        name = "招聘职位",
        packageName = "example.recruitment",
        className = "SiteJob",
        tableName = "site_job",
        kind = LowcodeModelKind.ENTITY,
        status = 1,
        version = 1,
        contributorId = "example.example",
        fields = emptyList(),
        queries = emptyList(),
        relations = emptyList(),
    )

    private fun routeBinding(
        model: LowcodeModelMeta,
        excel: LsiLowcodeExcel? = null,
    ): LowcodeRouteBinding {
        val route = LsiLowcodeRoute(
            packageName = model.packageName,
            qualifiedName = "example.recruitment.generated.entity.SiteJob",
            className = model.className,
            description = model.name,
            path = "/jobs",
            enabledOperations = setOf("GET", "PAGE"),
            excel = excel,
            properties = emptyList(),
            featurePackageName = model.packageName,
            modelCode = model.modelCode,
        )
        return LowcodeRouteBinding(route.qualifiedName, model.contributorId!!, route)
    }
}
