modules:
  - ./apps/client-contract
  - ./apps/dev-host
  - ./build-tools/*
  - ./modules/*

plugins:
  - ./build-tools/dto-analysis
  - ./build-tools/source-generation
  - ./build-tools/studio-ui
  - ./build-tools/report-ui
