package site.addzero.platform.lowcode.generator

/** 为 Studio 生成物添加统一且可搜索的首行标记。 */
fun generatedByStudio(
    content: String,
    extensionName: String = "kt",
): String {
    if (content.lineSequence().take(STUDIO_GENERATED_MARKER_LINE_LIMIT).any { line ->
            STUDIO_GENERATED_MARKER in line
        }
    ) {
        return content
    }
    val marker = when (extensionName) {
        "kt" -> "// $STUDIO_GENERATED_MARKER，请勿手工修改。"
        "sql" -> "-- $STUDIO_GENERATED_MARKER，请勿手工修改。"
        "md" -> "<!-- $STUDIO_GENERATED_MARKER，请勿手工修改。 -->"
        else -> error("Studio 生成文件不支持添加注释: $extensionName")
    }
    return "$marker\n$content"
}

const val STUDIO_GENERATED_MARKER = "generated by studio"
internal const val STUDIO_GENERATED_MARKER_LINE_LIMIT = 5
