package site.addzero.platform.lowcode.generator

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertFalse
import org.junit.jupiter.api.Assertions.assertThrows
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import site.addzero.dto.compiler.LsiDtoType
import site.addzero.validation.compiler.LsiValidationRule

class LowcodeDtoSourceGeneratorTest {
    @Test
    fun `generates empty structure as marker class`() {
        val definition = LsiLowcodeDtoDefinition(
            dtoCode = "marker",
            name = "标记结构",
            packageName = "example.marker",
            className = "Marker",
            kind = LowcodeDtoKind.STRUCTURE,
            contributorId = "example.example",
            fields = emptyList(),
        )

        val file = LowcodeDtoSourceGenerator.generateDefinitions(listOf(definition), emptyList()).single()

        assertTrue(file.content.contains("class Marker"))
        assertFalse(file.content.contains("data class Marker"))
    }

    @Test
    fun `generates structure dto from qualified Kotlin types without OpenAPI exposure`() {
        val definition = LsiLowcodeDtoDefinition(
            dtoCode = "toolSet",
            name = "工具集合",
            packageName = "example.tools",
            className = "ToolSet",
            kind = LowcodeDtoKind.STRUCTURE,
            contributorId = "example.example",
            fields = listOf(
                LsiLowcodeDtoField(
                    name = "registry",
                    nullability = LowcodeDtoNullability.NON_NULL,
                    kotlinType = LsiDtoType("example.registry.ToolRegistry"),
                ),
                LsiLowcodeDtoField(
                    name = "policies",
                    nullability = LowcodeDtoNullability.NON_NULL,
                    kotlinType = LsiDtoType.map(
                        LsiDtoType.STRING,
                        LsiDtoType("example.policy.ToolPolicy"),
                    ),
                ),
            ),
        )

        val file = LowcodeDtoSourceGenerator.generateDefinitions(listOf(definition), emptyList()).single()

        assertEquals(LowcodeGeneratedFileKind.COMPILED_SOURCE, file.kind)
        assertTrue(file.content.startsWith("// generated by studio"))
        assertTrue(file.content.contains("import example.policy.ToolPolicy"))
        assertTrue(file.content.contains("import example.registry.ToolRegistry"))
        assertTrue(file.content.contains("data class ToolSet"))
        assertTrue(file.content.contains("val policies: Map<String, ToolPolicy>"))
        assertThrows(IllegalArgumentException::class.java) { definition.toLsiDtoSchema() }
        assertTrue(LowcodeDtoSourceGenerator.generateDefinitionValidations(listOf(definition), emptyList()).isEmpty())
    }

    @Test
    fun `generates validation extension beside standalone input dto`() {
        val definition = LsiLowcodeDtoDefinition(
            dtoCode = "exampleCommand",
            name = "示例命令",
            packageName = "example.command",
            className = "ExampleCommand",
            kind = LowcodeDtoKind.INPUT,
            contributorId = "example.example",
            fields = listOf(
                LsiLowcodeDtoField(
                    name = "name",
                    nullability = LowcodeDtoNullability.NON_NULL,
                    schema = LsiLowcodeApiSchema(type = "string"),
                    validations = listOf(LsiValidationRule("notBlank", "名称不能为空")),
                ),
            ),
        )

        val file = LowcodeDtoSourceGenerator.generateDefinitionValidations(
            listOf(definition),
            emptyList(),
        ).single()

        assertEquals("ExampleCommandValidation", file.fileName)
        assertEquals("example.command.generated.dto", file.packageName)
        assertTrue(file.content.contains("fun ExampleCommand.validate(): ExampleCommand"))
        assertTrue(file.content.contains("this@validate.name.isBlank()"))
        assertTrue(file.content.contains("throw ValidationException"))
    }

    @Test
    fun `generates standalone dto without an entity model`() {
        val definition = LsiLowcodeDtoDefinition(
            dtoCode = "deviceStatusCount",
            name = "设备状态数量",
            packageName = "example.stats",
            className = "DeviceStatusCountOutput",
            kind = LowcodeDtoKind.OUTPUT,
            contributorId = "example.example",
            fields = listOf(
                LsiLowcodeDtoField(
                    name = "total",
                    nullability = LowcodeDtoNullability.NON_NULL,
                    schema = LsiLowcodeApiSchema(type = "integer", format = "int64"),
                    description = "设备总数",
                ),
                LsiLowcodeDtoField(
                    name = "label",
                    nullability = LowcodeDtoNullability.NULLABLE,
                    schema = LsiLowcodeApiSchema(type = "string"),
                ),
            ),
        )

        val file = LowcodeDtoSourceGenerator.generateDefinitions(listOf(definition), emptyList()).single()
        val schema = definition.toLsiDtoSchema(emptyList())

        assertEquals("example.stats.generated.dto", file.packageName)
        assertTrue(file.content.contains("data class DeviceStatusCountOutput"))
        assertTrue(file.content.contains("val total: Long"))
        assertTrue(file.content.contains("/** 设备总数 */"))
        assertTrue(file.content.contains("val label: String?"))
        assertEquals(LsiLowcodeDtoRef(dtoCode = "deviceStatusCount"), schema.ref)
        assertEquals(setOf("total"), schema.required)
        assertEquals("设备总数", schema.properties.getValue("total").description)
        assertEquals("设备状态数量", schema.description)
    }

    @Test
    fun `view dto imports the explicitly configured existing entity source`() {
        val model = newsModel().copy(
            entityConfig = newsModel().entityConfig.copy(
                sourceMode = LowcodeEntitySourceMode.EXISTING,
                sourceQualifiedName = "example.content.News",
            ),
        )

        val view = LowcodeDtoSourceGenerator.generate(listOf(model))
            .single { file -> file.fileName == "NewsListView" }

        assertTrue(view.content.contains("import example.content.News"))
        assertTrue(view.content.contains("fun News.toNewsListView()"))
        assertFalse(view.content.contains("example.news.generated.entity.News"))
    }

    @Test
    fun `view dto projects formula property from its entity`() {
        val model = newsModel().copy(
            entityConfig = newsModel().entityConfig.copy(
                formulaProperties = listOf(
                    LsiLowcodeFormulaProperty(
                        propertyCode = "displayTitle",
                        label = "展示标题",
                        kotlinType = "String",
                        kind = LowcodeFormulaKind.KOTLIN,
                        expression = "title.uppercase()",
                        dependencies = listOf("title"),
                    ),
                ),
            ),
            dtoDefinitions = listOf(
                LsiLowcodeDto(
                    dtoCode = "newsListView",
                    className = "NewsListView",
                    kind = LowcodeDtoKind.VIEW,
                    fields = listOf(LsiLowcodeDtoField("displayTitle")),
                ),
            ),
        )

        val view = LowcodeDtoSourceGenerator.generate(listOf(model)).single()
        val schema = model.toLsiDtoSchemas(listOf(model)).single()

        assertTrue(view.content.contains("val displayTitle: String"))
        assertTrue(view.content.contains("/** 展示标题 */"))
        assertTrue(view.content.contains("displayTitle = displayTitle"))
        assertTrue(schema.required.contains("displayTitle"))
        assertTrue(schema.properties.getValue("displayTitle").type == "string")
    }

    @Test
    fun `generates typed views input and entity mappings`() {
        val files = LowcodeDtoSourceGenerator.generate(listOf(newsModel()))
        val listView = files.single { file -> file.fileName == "NewsListView" }
        val request = files.single { file -> file.fileName == "NewsRequest" }

        assertTrue(listView.content.contains("val publishedAt: LocalDateTime?"))
        assertTrue(listView.content.contains("fun News.toNewsListView(): NewsListView"))
        assertTrue(listView.content.contains("publishedAt = publishedAt"))
        assertTrue(request.content.contains("val title: String,"))
        assertTrue(request.content.contains("val status: String? = null"))
        assertTrue(request.content.contains("val sortOrder: Int? = null"))
        assertTrue(request.content.contains("val enabled: Boolean? = null"))
        assertFalse(request.content.contains("fun News.toNewsRequest"))
    }

    @Test
    fun `removing dto metadata removes its generated file`() {
        val model = newsModel()
        val generated = LowcodeDtoSourceGenerator.generate(listOf(model))
        val afterDelete = LowcodeDtoSourceGenerator.generate(
            listOf(model.copy(dtoDefinitions = model.dtoDefinitions.filterNot { dto -> dto.dtoCode == "newsRequest" })),
        )

        assertTrue(generated.any { file -> file.fileName == "NewsRequest" })
        assertFalse(afterDelete.any { file -> file.fileName == "NewsRequest" })
    }

    @Test
    fun `view maps nullable relation fields and schemas from target metadata`() {
        val news = newsModel().copy(
            dtoDefinitions = listOf(
                LsiLowcodeDto(
                    dtoCode = "newsListView",
                    className = "NewsListView",
                    kind = LowcodeDtoKind.VIEW,
                    fields = listOf(LsiLowcodeDtoField("coverUrl", sourcePath = "coverFile.url")),
                ),
            ),
            relations = listOf(
                LowcodeRelationMeta(
                    id = 10,
                    modelId = 1,
                    orderNo = 1,
                    relationCode = "coverFile",
                    label = "coverFile",
                    relationKind = LowcodeRelationKind.MANY_TO_ONE,
                    targetModelId = 2,
                    targetModelCode = "storedFile",
                    targetPackageName = "example.file",
                    targetClassName = "StoredFile",
                    joinColumn = "cover_file_id",
                    mappedBy = null,
                    joinTable = null,
                    joinTableJoinColumn = null,
                    joinTableInverseColumn = null,
                    required = false,
                    listVisible = true,
                    formVisible = true,
                ),
            ),
        )
        val storedFile = newsModel().copy(
            id = 2,
            modelCode = "storedFile",
            packageName = "example.file",
            className = "StoredFile",
            dtoDefinitions = emptyList(),
            fields = listOf(field(20, "url", "String", "url", required = true).copy(modelId = 2)),
        )

        val view = LowcodeDtoSourceGenerator.generate(listOf(news, storedFile))
            .single { file -> file.fileName == "NewsListView" }
        val schema = news.toLsiDtoSchemas(listOf(news, storedFile)).single()

        assertTrue(view.content.contains("val coverUrl: String?"))
        assertTrue(view.content.contains("coverUrl = coverFile?.url"))
        assertTrue("coverUrl" !in schema.required)
        assertTrue(schema.properties.getValue("coverUrl").type == "string")
    }

    @Test
    fun `target model catalog resolves cross module relation without generating target dto`() {
        val news = newsModel().copy(
            dtoDefinitions = listOf(
                LsiLowcodeDto(
                    dtoCode = "newsListView",
                    className = "NewsListView",
                    kind = LowcodeDtoKind.VIEW,
                    fields = listOf(LsiLowcodeDtoField("coverUrl", sourcePath = "coverFile.url")),
                ),
            ),
            relations = listOf(fileRelation()),
        )
        val storedFile = storedFileModel()

        val files = LowcodeDtoSourceGenerator.generate(listOf(news), listOf(news, storedFile))

        assertTrue(files.single().content.contains("coverUrl = coverFile?.url"))
        assertFalse(files.any { file -> file.packageName == "example.file.generated.dto" })
    }

    @Test
    fun `input dto resolves generated relation id view`() {
        val news = newsModel().copy(
            dtoDefinitions = listOf(
                LsiLowcodeDto(
                    dtoCode = "newsRequest",
                    className = "NewsRequest",
                    kind = LowcodeDtoKind.INPUT,
                    fields = listOf(LsiLowcodeDtoField("coverFileId")),
                ),
            ),
            relations = listOf(fileRelation()),
        )

        val request = LowcodeDtoSourceGenerator.generate(listOf(news), listOf(news, storedFileModel())).single()
        val schema = news.toLsiDtoSchemas(listOf(news, storedFileModel())).single()

        assertTrue(request.content.contains("val coverFileId: Long? = null"))
        assertTrue(schema.properties.getValue("coverFileId").format == "int64")
    }

    @Test
    fun `selection modes expand metadata fields and apply reverse exclusions`() {
        val news = newsModel().copy(
            relations = listOf(fileRelation()),
            dtoDefinitions = listOf(
                LsiLowcodeDto(
                    dtoCode = "scalarView",
                    className = "ScalarView",
                    kind = LowcodeDtoKind.VIEW,
                    selectionMode = LowcodeDtoSelectionMode.ALL_SCALAR_FIELDS,
                    excludedPaths = listOf("status"),
                ),
                LsiLowcodeDto(
                    dtoCode = "tableView",
                    className = "TableView",
                    kind = LowcodeDtoKind.VIEW,
                    selectionMode = LowcodeDtoSelectionMode.ALL_TABLE_FIELDS,
                    excludedPaths = listOf("publishedAt"),
                ),
                LsiLowcodeDto(
                    dtoCode = "deepView",
                    className = "DeepView",
                    kind = LowcodeDtoKind.VIEW,
                    selectionMode = LowcodeDtoSelectionMode.ALL_DEEP_FIELDS,
                    excludedPaths = listOf("coverFile.url"),
                ),
            ),
        )

        val files = LowcodeDtoSourceGenerator.generate(listOf(news), listOf(news, storedFileModel()))
            .associateBy(LowcodeGeneratedFile::fileName)

        assertTrue(files.getValue("ScalarView").content.contains("val title: String"))
        assertFalse(files.getValue("ScalarView").content.contains("val status:"))
        assertFalse(files.getValue("ScalarView").content.contains("coverFileId"))
        assertTrue(files.getValue("TableView").content.contains("val coverFileId: Long?"))
        assertFalse(files.getValue("TableView").content.contains("publishedAt"))
        assertTrue(files.getValue("DeepView").content.contains("val coverFileId: Long?"))
        assertEquals(1, Regex("val coverFileId:").findAll(files.getValue("DeepView").content).count())
        assertFalse(files.getValue("DeepView").content.contains("coverFileUrl"))
    }

    @Test
    fun `entity schema exposes shallow association objects and generated id views`() {
        val base = newsModel()
        val model = base.copy(
            fields = base.fields.map { field ->
                if (field.fieldCode == "title") {
                    field.copy(label = "标题", remark = "对外展示的新闻标题")
                } else {
                    field
                }
            },
            relations = listOf(
                fileRelation().copy(label = "封面文件"),
                attachmentsRelation().copy(label = "附件"),
            ),
        )
        val storedFile = storedFileModel()

        val schema = model.toLsiEntitySchema(listOf(model, storedFile))
        val coverFile = schema.properties.getValue("coverFile")
        val attachments = schema.properties.getValue("attachments")
        val contractSource = LowcodeRouteSourceGenerator.toContractSource(
            LsiLowcodeContract(
                contractCode = "news",
                name = "新闻",
                packageName = "example.news",
                className = "NewsService",
                path = "/news",
                dtoSchemas = listOf(schema),
            ),
        )

        assertEquals(LsiLowcodeDtoRef("news"), schema.ref)
        assertEquals("news_entity", schema.schemaName)
        assertEquals("新闻", schema.description)
        assertEquals("对外展示的新闻标题", schema.properties.getValue("title").description)
        assertEquals("object", coverFile.type)
        assertEquals("封面文件", coverFile.description)
        assertEquals("integer", coverFile.properties.getValue("id").type)
        assertEquals("string", coverFile.properties.getValue("url").type)
        assertTrue(schema.properties.containsKey("coverFileId"))
        assertEquals("封面文件编号", schema.properties.getValue("coverFileId").description)
        assertEquals("array", attachments.type)
        assertEquals("string", attachments.items?.properties?.getValue("url")?.type)
        assertTrue(schema.properties.containsKey("attachmentIds"))
        assertEquals("附件编号集合", schema.properties.getValue("attachmentIds").description)
        assertTrue(contractSource.contains("description = \"新闻\""))
        assertTrue(contractSource.contains("description = \"对外展示的新闻标题\""))
    }

    private fun fileRelation() = LowcodeRelationMeta(
        id = 10,
        modelId = 1,
        orderNo = 1,
        relationCode = "coverFile",
        label = "coverFile",
        relationKind = LowcodeRelationKind.MANY_TO_ONE,
        targetModelId = 2,
        targetModelCode = "storedFile",
        targetPackageName = "example.file",
        targetClassName = "StoredFile",
        joinColumn = "cover_file_id",
        mappedBy = null,
        joinTable = null,
        joinTableJoinColumn = null,
        joinTableInverseColumn = null,
        required = false,
        listVisible = true,
        formVisible = true,
    )

    private fun attachmentsRelation() = fileRelation().copy(
        id = 11,
        orderNo = 2,
        relationCode = "attachments",
        relationKind = LowcodeRelationKind.MANY_TO_MANY,
        joinColumn = null,
        joinTable = "news_attachment",
        joinTableJoinColumn = "news_id",
        joinTableInverseColumn = "file_id",
    )

    private fun storedFileModel() = newsModel().copy(
        id = 2,
        modelCode = "storedFile",
        packageName = "example.file",
        className = "StoredFile",
        dtoDefinitions = emptyList(),
        fields = listOf(field(20, "url", "String", "url", required = true).copy(modelId = 2)),
    )

    private fun newsModel(): LowcodeModelMeta = LowcodeModelMeta(
        id = 1,
        modelCode = "news",
        name = "新闻",
        packageName = "example.news",
        className = "News",
        tableName = "cms_news",
        kind = LowcodeModelKind.ENTITY,
        status = 1,
        version = 1,
        contributorId = "example.example-news",
        entityConfig = LsiLowcodeEntityConfig(
            baseMode = LowcodeEntityBaseMode.INHERITED,
            superTypes = listOf("example.persistence.Record"),
            inheritedProperties = listOf(
                LsiLowcodeInheritedProperty("id", "Long", "id", required = true, id = true),
            ),
            microServiceName = null,
        ),
        dtoDefinitions = listOf(
            LsiLowcodeDto(
                dtoCode = "newsListView",
                className = "NewsListView",
                kind = LowcodeDtoKind.VIEW,
                fields = listOf(
                    LsiLowcodeDtoField("id"),
                    LsiLowcodeDtoField("title"),
                    LsiLowcodeDtoField("publishedAt"),
                ),
            ),
            LsiLowcodeDto(
                dtoCode = "newsRequest",
                className = "NewsRequest",
                kind = LowcodeDtoKind.INPUT,
                fields = listOf(
                    LsiLowcodeDtoField("title"),
                    LsiLowcodeDtoField("publishedAt"),
                    LsiLowcodeDtoField("status", nullability = LowcodeDtoNullability.NULLABLE),
                    LsiLowcodeDtoField("sortOrder", nullability = LowcodeDtoNullability.NULLABLE),
                    LsiLowcodeDtoField("enabled", nullability = LowcodeDtoNullability.NULLABLE),
                ),
            ),
        ),
        fields = listOf(
            field(1, "title", "String", "title", required = true),
            field(2, "publishedAt", "java.time.LocalDateTime", "published_at", required = false),
            field(3, "status", "String", "status", required = true),
            field(4, "sortOrder", "Int", "sort_order", required = true),
            field(5, "enabled", "Boolean", "enabled", required = true),
        ),
        queries = emptyList(),
        relations = emptyList(),
    )

    private fun field(
        id: Long,
        code: String,
        type: String,
        column: String,
        required: Boolean,
    ): LowcodeFieldMeta = LowcodeFieldMeta(
        id = id,
        modelId = 1,
        orderNo = id.toInt(),
        fieldCode = code,
        label = code,
        kotlinType = type,
        dbColumn = column,
        required = required,
        listVisible = true,
        formVisible = true,
        formControl = "input",
        dictCode = null,
        defaultValue = null,
        remark = null,
    )
}
