CREATE TABLE ${studioSchema}.metadata_contributor (
    id TEXT PRIMARY KEY,
    format_version INTEGER NOT NULL CHECK (format_version = 1),
    migration_location TEXT NOT NULL
);

CREATE TABLE ${studioSchema}.lowcode_definition (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP,
    creator BIGINT,
    updater BIGINT,
    code TEXT NOT NULL UNIQUE REFERENCES ${studioSchema}.metadata_contributor (id),
    display_name TEXT NOT NULL CHECK (btrim(display_name) <> ''),
    version INTEGER NOT NULL DEFAULT 1 CHECK (version > 0),
    status INTEGER NOT NULL DEFAULT 1,
    definition_type TEXT NOT NULL DEFAULT 'LIBRARY' CHECK (definition_type = 'LIBRARY')
);

CREATE TABLE ${studioSchema}.library_definition (
    id BIGINT PRIMARY KEY REFERENCES ${studioSchema}.lowcode_definition (id) ON DELETE CASCADE,
    spec JSONB NOT NULL DEFAULT '{}'::JSONB
);

CREATE TABLE ${studioSchema}.library_feature (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP,
    creator BIGINT,
    updater BIGINT,
    library_id BIGINT NOT NULL REFERENCES ${studioSchema}.library_definition (id) ON DELETE CASCADE,
    parent_id BIGINT REFERENCES ${studioSchema}.library_feature (id) ON DELETE RESTRICT,
    feature_code TEXT NOT NULL,
    name TEXT NOT NULL CHECK (btrim(name) <> ''),
    description TEXT,
    UNIQUE (library_id, feature_code)
);

CREATE INDEX idx_library_feature_library ON ${studioSchema}.library_feature (library_id);
CREATE INDEX idx_library_feature_parent ON ${studioSchema}.library_feature (parent_id);
