CREATE TABLE ${studioSchema}.lowcode_model (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP,
    creator BIGINT,
    updater BIGINT,
    feature_id BIGINT NOT NULL REFERENCES ${studioSchema}.library_feature (id) ON DELETE RESTRICT,
    model_code TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    class_name TEXT NOT NULL,
    table_name TEXT NOT NULL UNIQUE,
    model_type TEXT NOT NULL,
    status INTEGER NOT NULL DEFAULT 1,
    version INTEGER NOT NULL DEFAULT 1 CHECK (version > 0),
    remark TEXT,
    entity_config JSONB NOT NULL DEFAULT '{}'::JSONB,
    route_config JSONB,
    UNIQUE (feature_id, class_name)
);

CREATE INDEX idx_lowcode_model_feature ON ${studioSchema}.lowcode_model (feature_id);

CREATE TABLE ${studioSchema}.lowcode_field (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP,
    creator BIGINT,
    updater BIGINT,
    model_id BIGINT NOT NULL REFERENCES ${studioSchema}.lowcode_model (id) ON DELETE CASCADE,
    order_no INTEGER NOT NULL,
    field_code TEXT NOT NULL,
    label TEXT NOT NULL,
    kotlin_type TEXT NOT NULL,
    db_column TEXT NOT NULL,
    required BOOLEAN NOT NULL,
    list_visible BOOLEAN NOT NULL,
    form_visible BOOLEAN NOT NULL,
    form_control TEXT NOT NULL,
    dict_code TEXT,
    default_value TEXT,
    remark TEXT,
    serialized BOOLEAN NOT NULL DEFAULT FALSE,
    max_length INTEGER CHECK (max_length IS NULL OR max_length > 0),
    enum_storage TEXT CHECK (enum_storage IS NULL OR enum_storage IN ('NAME', 'ORDINAL')),
    natural_key BOOLEAN NOT NULL DEFAULT FALSE,
    create_writable BOOLEAN NOT NULL DEFAULT TRUE,
    update_writable BOOLEAN NOT NULL DEFAULT TRUE,
    UNIQUE (model_id, field_code),
    UNIQUE (model_id, db_column)
);

CREATE INDEX idx_lowcode_field_model ON ${studioSchema}.lowcode_field (model_id);

CREATE TABLE ${studioSchema}.lowcode_query (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP,
    creator BIGINT,
    updater BIGINT,
    model_id BIGINT NOT NULL REFERENCES ${studioSchema}.lowcode_model (id) ON DELETE CASCADE,
    order_no INTEGER NOT NULL,
    query_code TEXT NOT NULL,
    label TEXT NOT NULL,
    query_logic TEXT NOT NULL,
    UNIQUE (model_id, query_code)
);

CREATE INDEX idx_lowcode_query_model ON ${studioSchema}.lowcode_query (model_id);

CREATE TABLE ${studioSchema}.lowcode_query_condition (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP,
    creator BIGINT,
    updater BIGINT,
    query_id BIGINT NOT NULL REFERENCES ${studioSchema}.lowcode_query (id) ON DELETE CASCADE,
    order_no INTEGER NOT NULL,
    field_code TEXT NOT NULL,
    query_operator TEXT NOT NULL,
    value_type TEXT NOT NULL,
    param_name TEXT,
    UNIQUE (query_id, order_no)
);

CREATE INDEX idx_lowcode_query_condition_query ON ${studioSchema}.lowcode_query_condition (query_id);

CREATE TABLE ${studioSchema}.lowcode_relation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP,
    creator BIGINT,
    updater BIGINT,
    model_id BIGINT NOT NULL REFERENCES ${studioSchema}.lowcode_model (id) ON DELETE CASCADE,
    order_no INTEGER NOT NULL,
    relation_code TEXT NOT NULL,
    label TEXT NOT NULL,
    relation_type TEXT NOT NULL,
    target_model_id BIGINT,
    join_column TEXT,
    mapped_by TEXT,
    join_table TEXT,
    join_table_join_column TEXT,
    join_table_inverse_column TEXT,
    join_table_filter_column TEXT,
    join_table_filter_values JSONB,
    dissociate_action TEXT NOT NULL DEFAULT 'NONE',
    required BOOLEAN NOT NULL,
    list_visible BOOLEAN NOT NULL,
    form_visible BOOLEAN NOT NULL,
    create_writable BOOLEAN NOT NULL DEFAULT TRUE,
    update_writable BOOLEAN NOT NULL DEFAULT TRUE,
    UNIQUE (model_id, relation_code)
);

CREATE INDEX idx_lowcode_relation_model ON ${studioSchema}.lowcode_relation (model_id);
CREATE INDEX idx_lowcode_relation_target ON ${studioSchema}.lowcode_relation (target_model_id);

CREATE TABLE ${studioSchema}.lowcode_dictionary (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP,
    creator BIGINT,
    updater BIGINT,
    dictionary_code TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    generate_enum BOOLEAN NOT NULL DEFAULT FALSE,
    owner_model_id BIGINT REFERENCES ${studioSchema}.lowcode_model (id) ON DELETE SET NULL,
    enum_class_name TEXT,
    enum_storage TEXT NOT NULL DEFAULT 'NAME' CHECK (enum_storage IN ('NAME', 'ORDINAL')),
    status INTEGER NOT NULL DEFAULT 1
);

CREATE INDEX idx_lowcode_dictionary_owner_model ON ${studioSchema}.lowcode_dictionary (owner_model_id);

CREATE TABLE ${studioSchema}.lowcode_dictionary_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP,
    creator BIGINT,
    updater BIGINT,
    dictionary_id BIGINT NOT NULL REFERENCES ${studioSchema}.lowcode_dictionary (id) ON DELETE CASCADE,
    order_no INTEGER NOT NULL,
    value TEXT NOT NULL,
    label TEXT NOT NULL,
    enum_name TEXT,
    status INTEGER NOT NULL DEFAULT 1,
    UNIQUE (dictionary_id, value),
    UNIQUE (dictionary_id, order_no)
);

CREATE INDEX idx_lowcode_dictionary_item_dictionary ON ${studioSchema}.lowcode_dictionary_item (dictionary_id);

CREATE TABLE ${studioSchema}.lowcode_constant_group (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP,
    creator BIGINT,
    updater BIGINT,
    feature_id BIGINT NOT NULL REFERENCES ${studioSchema}.library_feature (id) ON DELETE RESTRICT,
    group_code TEXT NOT NULL UNIQUE,
    object_name TEXT NOT NULL,
    description TEXT NOT NULL,
    status INTEGER NOT NULL DEFAULT 1,
    UNIQUE (feature_id, object_name)
);

CREATE INDEX idx_lowcode_constant_group_feature ON ${studioSchema}.lowcode_constant_group (feature_id);

CREATE TABLE ${studioSchema}.lowcode_constant_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP,
    creator BIGINT,
    updater BIGINT,
    constant_group_id BIGINT NOT NULL REFERENCES ${studioSchema}.lowcode_constant_group (id) ON DELETE CASCADE,
    order_no INTEGER NOT NULL CHECK (order_no > 0),
    constant_name TEXT NOT NULL,
    value_type TEXT NOT NULL CHECK (value_type IN ('BOOLEAN', 'INT', 'LONG', 'STRING')),
    constant_value TEXT NOT NULL,
    description TEXT NOT NULL,
    status INTEGER NOT NULL DEFAULT 1,
    UNIQUE (constant_group_id, constant_name),
    UNIQUE (constant_group_id, order_no)
);

CREATE INDEX idx_lowcode_constant_item_group ON ${studioSchema}.lowcode_constant_item (constant_group_id);
