CREATE TABLE ${studioSchema}.lowcode_dto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP,
    creator BIGINT,
    updater BIGINT,
    feature_id BIGINT NOT NULL REFERENCES ${studioSchema}.library_feature (id) ON DELETE RESTRICT,
    dto_code TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    class_name TEXT NOT NULL,
    kind TEXT NOT NULL,
    visibility TEXT NOT NULL DEFAULT 'PUBLIC',
    source_model_id BIGINT REFERENCES ${studioSchema}.lowcode_model (id) ON DELETE SET NULL,
    selection_mode TEXT NOT NULL DEFAULT 'EXPLICIT',
    excluded_paths JSONB NOT NULL DEFAULT '[]'::JSONB,
    fields JSONB NOT NULL DEFAULT '[]'::JSONB,
    annotations JSONB NOT NULL DEFAULT '[]'::JSONB,
    super_types JSONB NOT NULL DEFAULT '[]'::JSONB,
    status INTEGER NOT NULL DEFAULT 1,
    version INTEGER NOT NULL DEFAULT 1 CHECK (version > 0),
    description TEXT,
    UNIQUE (feature_id, class_name)
);

CREATE INDEX idx_lowcode_dto_feature ON ${studioSchema}.lowcode_dto (feature_id);
CREATE INDEX idx_lowcode_dto_source_model ON ${studioSchema}.lowcode_dto (source_model_id);

CREATE TABLE ${studioSchema}.lowcode_api_contract (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP,
    creator BIGINT,
    updater BIGINT,
    feature_id BIGINT NOT NULL REFERENCES ${studioSchema}.library_feature (id) ON DELETE RESTRICT,
    contract_code TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    class_name TEXT NOT NULL,
    path TEXT NOT NULL,
    status INTEGER NOT NULL DEFAULT 1,
    version INTEGER NOT NULL DEFAULT 1 CHECK (version > 0),
    description TEXT,
    operations JSONB NOT NULL DEFAULT '[]'::JSONB,
    agent_exposure JSONB NOT NULL DEFAULT '{"operations":{}}'::JSONB,
    UNIQUE (feature_id, class_name)
);

CREATE INDEX idx_lowcode_api_contract_feature ON ${studioSchema}.lowcode_api_contract (feature_id);

CREATE TABLE ${studioSchema}.lowcode_route_binding (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP,
    creator BIGINT,
    updater BIGINT,
    route_code TEXT NOT NULL UNIQUE,
    contributor_id TEXT NOT NULL REFERENCES ${studioSchema}.metadata_contributor (id) ON DELETE RESTRICT,
    status INTEGER NOT NULL DEFAULT 1,
    version INTEGER NOT NULL DEFAULT 1 CHECK (version > 0),
    route_config JSONB NOT NULL
);

CREATE INDEX idx_lowcode_route_binding_contributor ON ${studioSchema}.lowcode_route_binding (contributor_id);

CREATE TABLE ${studioSchema}.lowcode_runtime_contract (
    contract_key TEXT PRIMARY KEY,
    contributor_id TEXT NOT NULL REFERENCES ${studioSchema}.metadata_contributor (id) ON DELETE RESTRICT,
    route_config JSONB,
    contract_config JSONB,
    CHECK (num_nonnulls(route_config, contract_config) = 1)
);

CREATE INDEX idx_lowcode_runtime_contract_contributor
    ON ${studioSchema}.lowcode_runtime_contract (contributor_id);

CREATE TABLE ${studioSchema}.lowcode_structure_analysis_snapshot (
    id INTEGER PRIMARY KEY CHECK (id = 1),
    schema_version INTEGER NOT NULL,
    source_fingerprint TEXT NOT NULL,
    metadata_fingerprint TEXT NOT NULL,
    generated_at_epoch_millis BIGINT NOT NULL,
    report JSONB NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
