CREATE TABLE ${studioSchema}.convention_file (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP,
    creator BIGINT,
    updater BIGINT,
    feature_id BIGINT NOT NULL REFERENCES ${studioSchema}.library_feature (id) ON DELETE RESTRICT,
    file_code TEXT NOT NULL,
    name TEXT NOT NULL,
    class_name TEXT NOT NULL,
    kind TEXT NOT NULL CHECK (kind IN ('SERVICE', 'SCHEDULED_JOB')),
    status INTEGER NOT NULL DEFAULT 1 CHECK (status IN (0, 1)),
    description TEXT,
    UNIQUE (feature_id, kind, file_code),
    UNIQUE (feature_id, class_name)
);

CREATE INDEX idx_convention_file_feature ON ${studioSchema}.convention_file (feature_id);
