tasks:
  buildStudioUi:
    action: !site.addzero.toolchain.lowcode.buildLowcodeStudio
      packageJson: ${module.rootDir}/../../ui/package.json
      lockFile: ${module.rootDir}/../../pnpm-lock.yaml
      indexFile: ${module.rootDir}/../../ui/index.html
      tsConfig: ${module.rootDir}/../../ui/tsconfig.json
      viteConfig: ${module.rootDir}/../../ui/vite.config.ts
      sourceDirectory: ${module.rootDir}/../../ui/src
      generatedResourcesDirectory: ${taskOutputDir}

generated:
  resources:
    - directory: ${tasks.buildStudioUi.action.generatedResourcesDirectory}
