package site.addzero.platform.lowcode.generator

import tools.jackson.databind.ObjectMapper

/** 把当前 contributor 使用的低代码 LSI 生成为业务数据库运行时快照。 */
object LowcodeRuntimeContractMigrationGenerator {
    const val GENERATED_MARKER = "-- generated by studio，请勿手工修改。"
    const val SNAPSHOT_FORMAT_VERSION = 1

    fun generate(
        contributorId: String,
        routes: Collection<LsiLowcodeRoute>,
        contracts: Collection<LsiLowcodeContract>,
    ): LowcodeGeneratedFile {
        val records = routes
            .map { route -> RuntimeContractRecord.model(route) } +
            contracts.map { contract -> RuntimeContractRecord.contract(contract) }
        val sortedRecords = records.sortedBy(RuntimeContractRecord::key)
        require(sortedRecords.map(RuntimeContractRecord::key).distinct().size == sortedRecords.size) {
            "运行时低代码契约键重复: ${sortedRecords.groupingBy(RuntimeContractRecord::key).eachCount().filterValues { it > 1 }.keys.sorted()}"
        }
        val contributorSlug = contributorId
            .trim(':')
            .replace(Regex("[^A-Za-z0-9]+"), "_")
            .lowercase()
        val fileName = "R__lowcode_runtime_contract_$contributorSlug"
        val content = buildString {
            appendLine(GENERATED_MARKER)
            appendLine("-- 运行时低代码契约快照格式: $SNAPSHOT_FORMAT_VERSION")
            appendLine("DO \$runtime_contract\$")
            appendLine("BEGIN")
            appendLine("    IF to_regclass('lowcode_runtime_contract') IS NULL THEN")
            appendLine("        RETURN;")
            appendLine("    END IF;")
            appendLine()
            appendLine("    DELETE FROM lowcode_runtime_contract")
            appendLine("    WHERE contributor_id = '${contributorId.escapeSqlLiteral()}';")
            if (sortedRecords.isNotEmpty()) {
                appendLine()
                appendLine("    INSERT INTO lowcode_runtime_contract (")
                appendLine("    contract_key,")
                appendLine("    contributor_id,")
                appendLine("    route_config,")
                appendLine("    contract_config")
                appendLine(")")
                appendLine("VALUES")
                appendLine(sortedRecords.joinToString(",\n") { record -> record.toSql(contributorId) })
                appendLine("ON CONFLICT (contract_key) DO UPDATE")
                appendLine("SET contributor_id = EXCLUDED.contributor_id,")
                appendLine("    route_config = EXCLUDED.route_config,")
                appendLine("    contract_config = EXCLUDED.contract_config;")
            }
            appendLine("END")
            appendLine("\$runtime_contract\$;")
        }
        return LowcodeGeneratedFile(
            packageName = "",
            fileName = fileName,
            relativePath = "src/main/resources/db/migration/$fileName.sql",
            content = generatedByStudio(content, extensionName = "sql"),
            extensionName = "sql",
            kind = LowcodeGeneratedFileKind.RUNTIME_METADATA,
        )
    }

    private data class RuntimeContractRecord(
        val key: String,
        val routeConfig: LsiLowcodeRoute?,
        val contractConfig: LsiLowcodeContract?,
    ) {
        fun toSql(contributorId: String): String {
            val routeJson = routeConfig?.toJsonSql() ?: "NULL"
            val contractJson = contractConfig?.toJsonSql() ?: "NULL"
            return "    ('${key.escapeSqlLiteral()}', '${contributorId.escapeSqlLiteral()}', $routeJson, $contractJson)"
        }

        companion object {
            fun model(route: LsiLowcodeRoute): RuntimeContractRecord {
                val modelCode = requireNotNull(route.modelCode?.takeIf(String::isNotBlank)) {
                    "运行时实体契约缺少 modelCode: ${route.qualifiedName}"
                }
                return RuntimeContractRecord("MODEL:$modelCode", route.normalizedForRuntime(), null)
            }

            fun contract(contract: LsiLowcodeContract): RuntimeContractRecord =
                RuntimeContractRecord("CONTRACT:${contract.contractCode}", null, contract.normalizedForRuntime())
        }
    }

    private fun Any.toJsonSql(): String {
        val json = OBJECT_MAPPER.writeValueAsString(this)
        require(JSON_DOLLAR_QUOTE !in json) {
            "低代码契约 JSON 包含保留的 SQL 定界符: $JSON_DOLLAR_QUOTE"
        }
        return "$JSON_DOLLAR_QUOTE $json $JSON_DOLLAR_QUOTE::JSONB"
    }

    private fun String.escapeSqlLiteral(): String = replace("'", "''")

    private fun LsiLowcodeRoute.normalizedForRuntime(): LsiLowcodeRoute = copy(
        aliasPaths = aliasPaths.sorted(),
        fetchPaths = fetchPaths.sorted(),
        excludePaths = excludePaths.sorted(),
        enabledOperations = enabledOperations.toSortedSet(),
        properties = properties.map { property -> property.copy(enumValues = property.enumValues.sorted()) },
        queryFields = queryFields.map { field -> field.copy(enumValues = field.enumValues.sorted()) },
        customOperations = customOperations.sortedBy(LsiLowcodeCustomOperation::operationCode),
        dtoSchemas = dtoSchemas.map { schema -> schema.normalizedForRuntime() }
            .sortedBy(LsiLowcodeDtoSchema::schemaName),
        agentExposure = agentExposure.normalizedForRuntime(),
    )

    private fun LsiLowcodeContract.normalizedForRuntime(): LsiLowcodeContract = copy(
        operations = operations.sortedBy(LsiLowcodeCustomOperation::operationCode),
        dtoSchemas = dtoSchemas.map { schema -> schema.normalizedForRuntime() }
            .sortedBy(LsiLowcodeDtoSchema::schemaName),
        agentExposure = agentExposure.normalizedForRuntime(),
    )

    private fun LsiAgentExposure.normalizedForRuntime(): LsiAgentExposure =
        copy(operations = operations.toSortedMap())

    private fun LsiLowcodeDtoSchema.normalizedForRuntime(): LsiLowcodeDtoSchema = copy(
        properties = properties.toSortedMap(),
        required = required.toSortedSet(),
        validations = validations.toSortedMap().mapValues { (_, rules) ->
            rules.sortedBy(site.addzero.validation.compiler.LsiValidationRule::code)
                .map { rule -> rule.copy(parameters = rule.parameters.toSortedMap()) }
        },
    )

    private val OBJECT_MAPPER = ObjectMapper()
    private const val JSON_DOLLAR_QUOTE = "${'$'}lowcode${'$'}"
}
