package site.addzero.platform.lowcode.generator

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertFalse
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test

class LowcodeFeatureReadmeGeneratorTest {
    @Test
    fun `按源码目录确定性生成功能说明`() {
        val model = LowcodeModelMeta(
            id = 1,
            modelCode = "siteJob",
            name = "招聘职位",
            packageName = "example.recruitment",
            className = "SiteJob",
            tableName = "site_job",
            kind = LowcodeModelKind.ENTITY,
            status = 1,
            version = 1,
            contributorId = "example.recruitment",
            fields = emptyList(),
            queries = emptyList(),
            relations = emptyList(),
        )
        val contract = LsiLowcodeContract(
            contractCode = "publicJob",
            name = "公开招聘",
            packageName = "example.recruitment",
            className = "PublicJobService",
            path = "/jobs",
            contributorId = model.contributorId,
        )
        val feature = LsiLowcodeFeature(
            featureCode = "recruitment",
            name = "招聘",
            description = "维护公开招聘职位。",
            packageName = "example.recruitment",
            contributorId = model.contributorId!!,
            modelCodes = listOf(model.modelCode),
            contractCodes = listOf(contract.contractCode),
        )

        val readme = LowcodeFeatureReadmeGenerator.generate(
            features = listOf(feature),
            models = listOf(model),
            contracts = listOf(contract),
        ).single()

        assertEquals("example.recruitment", readme.packageName)
        assertEquals("README", readme.fileName)
        assertEquals("md", readme.extensionName)
        assertEquals(
            "src/main/kotlin/example/recruitment/README.md",
            readme.relativePath,
        )
        assertTrue(readme.content.startsWith("<!-- generated by studio"))
        assertTrue(readme.content.contains("# 招聘模块\n"))
        assertTrue(readme.content.contains("| `recruitment` |"))
        assertTrue(readme.content.contains("| `siteJob` | 招聘职位 | `example.recruitment.generated.entity.SiteJob` |"))
        assertTrue(readme.content.contains("| 招聘职位 Service | `example.recruitment.generated.service.SiteJobService` |"))
        assertTrue(readme.content.contains("| 公开招聘 | `example.recruitment.generated.service.PublicJobService` |"))
        assertTrue(readme.content.endsWith("\n"))
    }

    @Test
    fun `无资源功能只生成说明不生成空 Service`() {
        val feature = LsiLowcodeFeature(
            featureCode = "dashboard",
            name = "管理看板",
            packageName = "example.dashboard",
            contributorId = "example.dashboard",
        )

        val readme = LowcodeFeatureReadmeGenerator.generate(listOf(feature), emptyList(), emptyList()).single()
        val services = LowcodeFeatureServiceSourceGenerator.generate(
            features = listOf(feature),
            models = emptyList(),
            contracts = emptyList(),
            routeBindings = emptyList(),
        )

        assertTrue(readme.content.contains("## 实体\n\n无。"))
        assertTrue(readme.content.contains("## Service\n\n无。"))
        assertTrue(services.isEmpty())
    }

    @Test
    fun `仅 existing REST 操作的契约不列出不存在的 Service`() {
        val contributorId = "example.example"
        val contract = LsiLowcodeContract(
            contractCode = "existingNews",
            name = "既有新闻接口",
            packageName = "example.news",
            className = "ExistingNewsService",
            path = "/news",
            contributorId = contributorId,
            operations = listOf(
                LsiLowcodeCustomOperation(
                    operationCode = "listNews",
                    name = "查询新闻",
                    path = "/news",
                    implementation = LowcodeOperationImplementation.EXISTING_REST,
                ),
            ),
        )
        val feature = LsiLowcodeFeature(
            featureCode = "news",
            name = "新闻",
            packageName = "example.news",
            contributorId = contributorId,
            contractCodes = listOf(contract.contractCode),
        )

        val readme = LowcodeFeatureReadmeGenerator.generate(
            features = listOf(feature),
            models = emptyList(),
            contracts = listOf(contract),
        ).single()

        assertTrue(readme.content.contains("## Service\n\n无。"))
        assertFalse(readme.content.contains("ExistingNewsService"))
    }

    @Test
    fun `父功能只列出直接子功能`() {
        val parent = LsiLowcodeFeature(
            featureCode = "inspection",
            name = "巡检",
            packageName = "example.inspection",
            contributorId = "example.example",
        )
        val task = parent.copy(
            featureCode = "inspection.task",
            name = "巡检任务",
            packageName = "example.inspection.task",
        )
        val execution = task.copy(
            featureCode = "inspection.task.execution",
            name = "任务执行",
            packageName = "example.inspection.task.execution",
        )

        val readmes = LowcodeFeatureReadmeGenerator.generate(
            listOf(parent, task, execution),
            emptyList(),
            emptyList(),
        )
        val parentReadme = readmes.single { it.packageName == parent.packageName }

        assertTrue(parentReadme.content.contains("| `inspection.task` | 巡检任务 |"))
        assertFalse(parentReadme.content.contains("| `inspection.task.execution` | 任务执行 |"))
    }

    @Test
    fun `转义会破坏 Markdown 结构的元数据`() {
        val feature = LsiLowcodeFeature(
            featureCode = "content",
            name = "内容 | `发布`",
            description = "第一行\n第二行",
            packageName = "example.content",
            contributorId = "example.example",
        )

        val content = LowcodeFeatureReadmeGenerator.generate(listOf(feature), emptyList(), emptyList())
            .single()
            .content

        assertTrue(content.startsWith("<!-- generated by studio"))
        assertTrue(content.contains("# 内容 \\| \\`发布\\`模块\n"))
        assertTrue(content.contains("第一行<br>第二行"))
    }
}
