import {
  ArchiveRestore,
  ArrowLeft,
  Blocks,
  BookOpen,
  Bot,
  ChartColumn,
  ChartNoAxesCombined,
  Circle,
  Database,
  Eye,
  FolderOpen,
  GripVertical,
  Hash,
  Image as ImageIcon,
  Library,
  Maximize2,
  MessageSquarePlus,
  MessagesSquare,
  PanelRight,
  PanelsLeftBottom,
  PanelsTopLeft,
  Play,
  Plus,
  Printer,
  Redo2,
  RefreshCw,
  Rows3,
  Save,
  Scan,
  Send,
  Settings,
  Table2,
  Trash2,
  Type,
  Undo2,
  ZoomIn,
  ZoomOut,
  type LucideIcon,
} from 'lucide-react'

const icons: Readonly<Record<string, LucideIcon>> = {
  'archive-restore': ArchiveRestore,
  'arrow-left': ArrowLeft,
  blocks: Blocks,
  'book-open': BookOpen,
  bot: Bot,
  'chart-column': ChartColumn,
  'chart-no-axes-combined': ChartNoAxesCombined,
  database: Database,
  eye: Eye,
  'folder-open': FolderOpen,
  'grip-vertical': GripVertical,
  hash: Hash,
  image: ImageIcon,
  library: Library,
  'maximize-2': Maximize2,
  'message-square-plus': MessageSquarePlus,
  'messages-square': MessagesSquare,
  'panel-right': PanelRight,
  'panels-left-bottom': PanelsLeftBottom,
  'panels-top-left': PanelsTopLeft,
  play: Play,
  plus: Plus,
  printer: Printer,
  'redo-2': Redo2,
  'refresh-cw': RefreshCw,
  'rows-3': Rows3,
  save: Save,
  scan: Scan,
  send: Send,
  settings: Settings,
  'table-2': Table2,
  'trash-2': Trash2,
  type: Type,
  'undo-2': Undo2,
  'zoom-in': ZoomIn,
  'zoom-out': ZoomOut,
}

export function CatalogIcon({ name, ...props }: Readonly<{ name?: string | null; className?: string }>) {
  const Icon = (name && icons[name]) || Circle
  return <Icon aria-hidden="true" {...props} />
}
