package site.addzero.platform.lowcode.generator

import java.security.MessageDigest

/** 把最小约定元数据生成为可编辑的业务源码。 */
object ConventionFileSourceGenerator {
    const val EDITABLE_CONVENTION_FILE_MARKER =
        "// generated by studio，约定文件首次生成后由业务代码维护。"
    const val SIGNATURE_PREFIX = "// 约定文件脚手架签名: "

    fun generate(
        files: List<LsiConventionFile>,
        templates: SourceTemplateCatalog = SourceTemplateCatalog.DEFAULT,
    ): List<LowcodeGeneratedFile> = files
        .sortedWith(compareBy(LsiConventionFile::packageName, LsiConventionFile::kind, LsiConventionFile::fileCode))
        .map { file -> generate(file, templates) }

    private fun generate(
        file: LsiConventionFile,
        templates: SourceTemplateCatalog,
    ): LowcodeGeneratedFile = when (file.kind) {
        LsiConventionFileKind.SERVICE -> generateService(file, templates)
        LsiConventionFileKind.SCHEDULED_JOB -> generateScheduledJob(file, templates)
    }

    private fun generateService(
        file: LsiConventionFile,
        templates: SourceTemplateCatalog,
    ): LowcodeGeneratedFile {
        val packageName = file.packageName(LowcodeScaffoldResourceKind.SERVICE)
        val header = file.header(packageName, listOf("org.koin.core.annotation.Single"))
        val content = templates.render(
            SourceTemplateKind.CONVENTION_SERVICE,
            mapOf(
                "header" to header,
                "documentation" to file.kdoc(),
                "className" to file.className,
            ),
        )
        return file.generatedFile(packageName, LowcodeScaffoldResourceKind.SERVICE, content)
    }

    private fun generateScheduledJob(
        file: LsiConventionFile,
        templates: SourceTemplateCatalog,
    ): LowcodeGeneratedFile {
        val packageName = file.packageName(LowcodeScaffoldResourceKind.SCHEDULED_JOB)
        val imports = listOf(
            "org.koin.core.annotation.Single",
            "${generationTargetSymbol(GenerationTargetSymbols.CORE_RUNTIME_PACKAGE)}.ScheduledJob",
        )
        val header = file.header(packageName, imports)
        val content = templates.render(
            SourceTemplateKind.SCHEDULED_JOB,
            mapOf(
                "header" to header,
                "documentation" to file.kdoc(),
                "className" to file.className,
            ),
        )
        return file.generatedFile(packageName, LowcodeScaffoldResourceKind.SCHEDULED_JOB, content)
    }

    private fun LsiConventionFile.header(
        packageName: String,
        imports: List<String>,
    ): String = """
        |$EDITABLE_CONVENTION_FILE_MARKER
        |${signature(this)}
        |package $packageName
        |
        |${imports.sorted().joinToString("\n") { importName -> "import $importName" }}
    """.trimMargin()

    private fun LsiConventionFile.generatedFile(
        packageName: String,
        resourceKind: LowcodeScaffoldResourceKind,
        content: String,
    ): LowcodeGeneratedFile {
        return LowcodeGeneratedFile(
            packageName = packageName,
            fileName = className,
            relativePath = this.packageName.generatedLayout().relativeScaffoldSourcePath(resourceKind, className),
            content = content,
            kind = LowcodeGeneratedFileKind.CONVENTION_FILE_SCAFFOLD,
        )
    }

    private fun LsiConventionFile.packageName(kind: LowcodeScaffoldResourceKind): String =
        packageName.generatedLayout().scaffoldPackageName(kind)

    private fun LsiConventionFile.kdoc(): String {
        val lines = listOf(name) + description.orEmpty().lineSequence().filter(String::isNotBlank).toList()
        return if (lines.size == 1) {
            "/** ${lines.single().escapeKDoc()}。 */"
        } else {
            lines.joinToString(separator = "\n * ", prefix = "/**\n * ", postfix = "\n */") { line ->
                line.escapeKDoc()
            }
        }
    }

    private fun signature(file: LsiConventionFile): String {
        val value = listOf(file.contributorId, file.packageName, file.kind.name, file.fileCode, file.className)
            .joinToString("|")
        val digest = MessageDigest.getInstance("SHA-256")
            .digest(value.toByteArray())
            .joinToString("") { byte -> "%02x".format(byte) }
        return "$SIGNATURE_PREFIX$digest"
    }

    private fun String.escapeKDoc(): String = replace("*/", "* /")
}
