package site.addzero.platform.lowcode.generator

import java.security.MessageDigest

/** 为实体生成首次创建后由业务代码维护的 Ktor CRUD Controller。 */
object LowcodeFeatureControllerSourceGenerator {
    const val EDITABLE_CONTROLLER_MARKER =
        "// generated by studio，Controller 首次生成后由业务代码维护。"
    const val CONTROLLER_SIGNATURE_PREFIX = "// 低代码 Controller 脚手架签名: "

    /** 校验可编辑 Controller 仍保留生成的 CRUD 主干。 */
    fun editableControllerScaffoldMismatches(
        actualContent: String,
        expectedContent: String,
    ): List<String> {
        val markerPresent = actualContent.lineSequence()
            .take(EDITABLE_CONTROLLER_HEADER_LINE_LIMIT)
            .any { line -> line.trim() == EDITABLE_CONTROLLER_MARKER }
        val signaturePresent = actualContent.lineSequence()
            .take(EDITABLE_CONTROLLER_HEADER_LINE_LIMIT)
            .any { line -> line.startsWith(CONTROLLER_SIGNATURE_PREFIX) }
        if (!markerPresent || !signaturePresent) {
            return emptyList()
        }

        val expected = expectedContent.requireControllerScaffold()
        val actualWithoutComments = actualContent.replace(KOTLIN_COMMENT_PATTERN, "")
        val classHeader = Regex("""\bclass\s+${Regex.escape(expected.controllerName)}\b[^{]*\{""")
            .find(actualWithoutComments)
            ?.value
            ?: return listOf("缺少预期类声明: ${expected.controllerName}")
        return buildList {
            val primaryController = Regex(
                """\b${Regex.escape(expected.primaryControllerType)}\s*<\s*${Regex.escape(expected.entityName)}\s*>""",
            )
            if (!primaryController.containsMatchIn(classHeader)) {
                add("缺少 ${expected.primaryControllerType}<${expected.entityName}>")
            }
            val routeKey = Regex(
                """\boverride\s+val\s+routeKey(?:\s*:\s*String)?\s*=\s*${Regex.escape(expected.routeKeyLiteral)}""",
            )
            if (!routeKey.containsMatchIn(actualWithoutComments)) {
                add("routeKey 不匹配，期望 ${expected.routeKeyLiteral}")
            }
        }
    }

    fun generate(
        features: List<LsiLowcodeFeature>,
        models: List<LowcodeModelMeta>,
        routeBindings: List<LowcodeRouteBinding>,
    ): List<LowcodeGeneratedFile> {
        val modelCodes = features.flatMap(LsiLowcodeFeature::modelCodes).toSet()
        return models
            .filter { model -> model.modelCode in modelCodes && model.kind == LowcodeModelKind.ENTITY }
            .map { model -> model to model.resolveRouteBinding(routeBindings) }
            .filter { (_, route) -> route.generatesEntityController() }
            .distinctBy { (_, route) -> route.qualifiedName }
            .sortedBy { (_, route) -> route.qualifiedName }
            .map { (model, route) ->
                route.requireValidExcelMetadata()
                generateController(route, model)
            }
    }

    private fun generateController(route: LsiLowcodeRoute, model: LowcodeModelMeta): LowcodeGeneratedFile {
        val layout = route.featurePackageName.generatedLayout()
        val packageName = layout.packageName(LowcodeGeneratedResourceKind.CONTROLLER)
        val controllerName = route.className + "Controller"
        val serviceName = route.className + "Service"
        val serviceQualifiedName = layout.qualifiedName(LowcodeGeneratedResourceKind.SERVICE, serviceName)
        val hasExcelCapability = route.excel?.let { excel -> excel.importEnabled || excel.exportEnabled } == true
        val hasGraphCapability = model.entityConfig.resolvedBaseModels()
            .any { definition -> definition.model == LowcodeBaseModel.NODE }
        val primaryControllerType = if (hasGraphCapability) "GraphController" else "CrudController"
        val controllerTypes = buildList {
            add("$primaryControllerType<${route.className}>")
            if (hasExcelCapability) {
                add("ExcelController<${route.className}>")
            }
        }
        val imports = sortedSetOf(
            "org.koin.core.annotation.Single",
            route.qualifiedName,
            serviceQualifiedName,
            "${generationTargetSymbol(GenerationTargetSymbols.LOWCODE_RUNTIME_PACKAGE)}.$primaryControllerType",
        )
        if (hasExcelCapability) {
            imports += "${generationTargetSymbol(GenerationTargetSymbols.LOWCODE_RUNTIME_PACKAGE)}.ExcelController"
        }
        val content = """
            |$EDITABLE_CONTROLLER_MARKER
            |$CONTROLLER_SIGNATURE_PREFIX${route.controllerSignature(hasGraphCapability)}
            |package $packageName
            |
            |${imports.joinToString("\n") { importName -> "import $importName" }}
            |
            |/**
            | * ${route.displayName ?: route.className} CRUD Controller。
            | *
            | * 本文件首次由低代码元数据生成，后续由业务代码维护。
            | */
            |@Single
            |class $controllerName(
            |    override val service: $serviceName,
            |) : ${controllerTypes.joinToString()} {
            |    override val routeKey = "${route.path.escapeKotlin()}"
            |}
        """.trimMargin().lineSequence().joinToString("\n") { line -> line.trimEnd() } + "\n"
        return LowcodeGeneratedFile(
            packageName = packageName,
            fileName = controllerName,
            relativePath = layout.relativeSourcePath(
                LowcodeGeneratedResourceKind.CONTROLLER,
                controllerName,
            ),
            content = content,
            kind = LowcodeGeneratedFileKind.CONTROLLER_SCAFFOLD,
        )
    }

    private fun LowcodeModelMeta.resolveRouteBinding(bindings: List<LowcodeRouteBinding>): LsiLowcodeRoute =
        requireNotNull(
            bindings.firstOrNull { binding ->
                binding.contributorId == contributorId &&
                    binding.route.className == className &&
                    binding.route.packageName == packageName
            }?.route,
        ) {
            "实体 Controller 缺少路由元数据: $modelCode"
        }

    private fun LsiLowcodeRoute.controllerSignature(hasGraphCapability: Boolean): String {
        val signatureParts = mutableListOf(
            path,
            aliasPaths.sorted().joinToString(),
            authenticated.toString(),
            enabledOperations.sorted().joinToString(),
            tree.toString(),
            excel?.let { value -> "${value.importEnabled}:${value.exportEnabled}" }.orEmpty(),
        )
        if (hasGraphCapability) {
            signatureParts += "GRAPH"
        }
        if (customOperations.isNotEmpty()) {
            val customOperationSignature = customOperations
                .sortedBy(LsiLowcodeCustomOperation::operationCode)
                .map(LsiLowcodeCustomOperation::controllerSignatureSource)
                .lengthPrefixed()
            signatureParts += customOperationSignature
        }
        val value = signatureParts.joinToString("|")
        return MessageDigest.getInstance("SHA-256")
            .digest(value.toByteArray())
            .joinToString("") { byte -> "%02x".format(byte) }
    }

    private fun String.escapeKotlin(): String = replace("\\", "\\\\")
        .replace("\"", "\\\"")
        .replace("\$", "\\\$")
}

private data class EditableControllerScaffold(
    val controllerName: String,
    val primaryControllerType: String,
    val entityName: String,
    val routeKeyLiteral: String,
)

private fun String.requireControllerScaffold(): EditableControllerScaffold {
    val declaration = requireNotNull(EXPECTED_CONTROLLER_DECLARATION.find(this)) {
        "生成的低代码 Controller 脚手架结构不合法"
    }
    val routeKey = requireNotNull(EXPECTED_ROUTE_KEY.find(this)) {
        "生成的低代码 Controller 缺少 routeKey"
    }
    return EditableControllerScaffold(
        controllerName = declaration.groupValues[1],
        primaryControllerType = declaration.groupValues[3],
        entityName = declaration.groupValues[4],
        routeKeyLiteral = routeKey.groupValues[1],
    )
}

private val EXPECTED_CONTROLLER_DECLARATION = Regex(
    """class\s+([A-Za-z_][A-Za-z0-9_]*)\s*\(\s*override\s+val\s+service\s*:\s*([A-Za-z_][A-Za-z0-9_]*)\s*,\s*\)\s*:\s*(CrudController|GraphController)\s*<\s*([A-Za-z_][A-Za-z0-9_.]*)\s*>""",
)
private val EXPECTED_ROUTE_KEY = Regex(
    """override\s+val\s+routeKey\s*=\s*(\"(?:\\.|[^\"\\])*\")""",
)
private val KOTLIN_COMMENT_PATTERN = Regex("""(?s)/\*.*?\*/|//[^\r\n]*""")
private const val EDITABLE_CONTROLLER_HEADER_LINE_LIMIT = 10

private fun LsiLowcodeCustomOperation.controllerSignatureSource(): String = listOf(
    operationCode,
    name,
    description.orEmpty(),
    path,
    method.name,
    transport.name,
    authenticated.toString(),
    suspending.toString(),
    permission.orEmpty(),
    callContext.toString(),
    parameters
        .sortedWith(compareBy(LsiLowcodeApiParameter::location, LsiLowcodeApiParameter::name))
        .map(LsiLowcodeApiParameter::controllerSignatureSource)
        .lengthPrefixed(),
    requestBody?.controllerSignatureSource().orEmpty(),
    responseBody?.controllerSignatureSource().orEmpty(),
    responseEnvelope.toString(),
    implementation.name,
).lengthPrefixed()

private fun LsiLowcodeApiParameter.controllerSignatureSource(): String = listOf(
    name,
    location.name,
    required.toString(),
    description.orEmpty(),
    schema.controllerSignatureSource(),
).lengthPrefixed()

private fun LsiLowcodeApiBody.controllerSignatureSource(): String = listOf(
    contentType,
    required.toString(),
    schema.controllerSignatureSource(),
    description.orEmpty(),
).lengthPrefixed()

private fun LsiLowcodeApiSchema.controllerSignatureSource(): String = listOf(
    type.orEmpty(),
    typeRef?.let { ref -> listOf(ref.modelCode.orEmpty(), ref.dtoCode).lengthPrefixed() }.orEmpty(),
    kotlinType?.canonicalName().orEmpty(),
    format.orEmpty(),
    description.orEmpty(),
    properties.toSortedMap().map { (name, property) ->
        listOf(name, property.controllerSignatureSource()).lengthPrefixed()
    }.lengthPrefixed(),
    required.sorted().lengthPrefixed(),
    items?.controllerSignatureSource().orEmpty(),
    enumValues.sorted().lengthPrefixed(),
    oneOf.map(LsiLowcodeApiSchema::controllerSignatureSource).sorted().lengthPrefixed(),
).lengthPrefixed()

private fun List<String>.lengthPrefixed(): String =
    joinToString(separator = "") { value -> "${value.length}:$value" }
