package site.addzero.platform.lowcode.generator

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertThrows
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test

class LowcodeGeneratedFileTest {
    @Test
    fun `所有 Studio 生成物使用统一注释标记`() {
        val kotlin = generatedByStudio("package example\n")
        val sql = generatedByStudio("SELECT 1;\n", extensionName = "sql")
        val markdown = generatedByStudio("# Example\n", extensionName = "md")

        assertTrue(kotlin.startsWith("// generated by studio"))
        assertTrue(sql.startsWith("-- generated by studio"))
        assertTrue(markdown.startsWith("<!-- generated by studio"))
        assertEquals(kotlin, generatedByStudio(kotlin))
    }

    @Test
    fun `生成文件缺少 Studio 标记时拒绝构造`() {
        assertThrows(IllegalArgumentException::class.java) {
            LowcodeGeneratedFile(
                packageName = "example.generated",
                fileName = "Example",
                relativePath = "example/generated/Example.kt",
                content = "package example.generated\n",
            )
        }
    }
}
